name: kikoenai
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.10.2+1

environment:
  sdk: '>=3.0.0 <4.0.0'
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
    - assets/animation/
dependencies:
  flutter:
    sdk: flutter
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.0.3
  palette_generator: ^0.3.3
  extended_image: ^10.0.1
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  bitsdojo_window: ^0.1.6
  google_fonts: ^6.3.2
  json_annotation: ^4.9.0
  go_router: ^16.0.0
  logging: ^1.2.0
  equatable: ^2.0.5
  freezed_annotation: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.4.0
  uuid: ^4.5.2
  shimmer: ^3.0.0
  skeletonizer: ^2.1.0
  wolt_modal_sheet: ^0.11.0
  just_audio: ^0.10.5
  just_audio_media_kit: any
  media_kit: ^1.2.0
  media_kit_libs_windows_audio: any
  audio_service: ^0.18.12
  rxdart: ^0.28.0
  smtc_windows: ^0.1.3
  audio_video_progress_bar: ^2.0.3
  permission_handler: ^12.0.1
  device_info_plus: ^10.1.0
  scroll_to_index: ^3.0.1
  archive: ^4.0.7
  file_picker: ^10.3.7   # 用于选择文件/文件夹
  fast_gbk: ^1.0.0
  scrollable_positioned_list: ^0.3.8
  audio_metadata_reader: ^1.4.2
  lottie: ^3.3.2
  logger: ^2.4.0
  url_launcher: ^6.3.2
  crypto: ^3.0.7
  open_filex: ^4.7.0
  back_button_interceptor: ^8.0.4
  native_flutter_proxy: ^0.3.1
  msix: ^3.16.12
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  custom_lint:
  riverpod_lint: ^3.0.3
  hive_test: ^1.0.0
  freezed: ^3.0.0
  hive_ce_generator: ^1.9.3

msix_config:
  display_name: Kikoenai
  publisher: CN=SignPath Foundation, O=SignPath Foundation, L=Lewes, S=Delaware, C=US
  logo_path: assets/images/muzumi.jpg